//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Nullinside.Cicd.GitHub.GraphQl.Model;


public partial class GraphQlGenericMutationResponse
{
    [JsonProperty("data")]
    public object Data { get; set; }
}
