//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace Nullinside.Cicd.GitHub.Model;

public class GraphQlProjectIssueResponse {
  [JsonProperty("data")] public Data Data { get; set; }
}

public class Data {
  [JsonProperty("repository")] public Repository Repository { get; set; }
}

public class Repository {
  [JsonProperty("id")] public string Id { get; set; }

  [JsonProperty("issues")] public Issues Issues { get; set; }
}

public class Issues {
  [JsonProperty("nodes")] public List<IssuesNode> Nodes { get; set; }

  [JsonProperty("pageInfo")] public PageInfo PageInfo { get; set; }
}

public class IssuesNode {
  [JsonProperty("number")] public long Number { get; set; }

  [JsonProperty("closed")] public bool Closed { get; set; }

  [JsonProperty("id")] public string Id { get; set; }

  [JsonProperty("projectItems")] public ProjectItems ProjectItems { get; set; }
}

public class ProjectItems {
  [JsonProperty("nodes")] public List<ProjectItemsNode> Nodes { get; set; }

  [JsonProperty("pageInfo")] public PageInfo PageInfo { get; set; }
}

public class ProjectItemsNode {
  [JsonProperty("fieldValueByName")] public FieldValueByName FieldValueByName { get; set; }

  [JsonProperty("id")] public string Id { get; set; }
}

public class FieldValueByName {
  [JsonProperty("field")] public Field Field { get; set; }

  [JsonProperty("name")] public string Name { get; set; }
}

public class Field {
  [JsonProperty("id")] public string Id { get; set; }
}

public class PageInfo {
  [JsonProperty("hasNextPage")] public bool HasNextPage { get; set; }
}